// ============================================================================
// DigiLog 360 — friendly domain type aliases derived from the DB schema
// ============================================================================
import type { Database } from './database.types';

// NOTE: database.types.ts is regenerated by `npm run db:types` once the new
// 20260603 migration is deployed. Until that runs, we widen a few types here
// so the apps still compile against the older generated file.
export type AppRole =
  | 'super_user'
  | 'admin'
  | 'manager'
  | 'control_room'
  | 'supervisor'
  | 'guard';

type DbEnums = Database['public']['Enums'];
export type SeverityLevel = DbEnums['severity_level'];
export type OccurrenceStatus = DbEnums['occurrence_status'];
export type PatrolStatus = DbEnums['patrol_status'];
export type ScanMethod = DbEnums['scan_method'];

type T = Database['public']['Tables'];
type V = Database['public']['Views'];

// Domain rows. We layer org_id / employee_number / pin metadata onto the
// generated row types so apps see them before db:types is regenerated.
type WithOrg<R> = R & { org_id: string };

export type Site = WithOrg<T['sites']['Row']>;
export type Profile = Omit<WithOrg<T['profiles']['Row']>, 'role'> & {
  role: AppRole;
  /** Full set of roles held by this user. `role` is always `roles[0]`. */
  roles: AppRole[];
  employee_number: string | null;
  pin_hash: string | null;
  pin_set_at: string | null;
  last_pin_login_at: string | null;
  /** Per-user override: shows the "Management Reports" option on the Log
   *  Occurrence form even if the user's role lacks the capability. Managed at
   *  /super/management-reports. */
  can_log_management_report: boolean;
};
export type Occurrence = WithOrg<T['occurrences']['Row']>;
export type OccurrenceInsert = T['occurrences']['Insert'] & { org_id?: string };
export type OccurrenceUpdate = WithOrg<T['occurrence_updates']['Row']>;
export type OccurrenceReport = WithOrg<T['occurrence_reports']['Row']>;
export type OccurrenceImage = WithOrg<T['occurrence_images']['Row']>;
/** A playable audio clip attached to an occurrence (bucket: occurrence-voice-notes).
 *  Manual type until database.types.ts is regenerated for the new table. */
export interface OccurrenceVoiceNote {
  id: number;
  occurrence_id: number;
  ob_number: string | null;
  storage_path: string;
  duration_ms: number | null;
  recorded_by: string | null;
  recorded_by_name: string | null;
  created_at: string;
}
export type PatrolRoute = WithOrg<T['patrol_routes']['Row']>;
export type Checkpoint = WithOrg<T['checkpoints']['Row']>;
export type RouteCheckpoint = WithOrg<T['route_checkpoints']['Row']>;
export type Patrol = WithOrg<T['patrols']['Row']>;
export type CheckpointScan = WithOrg<T['checkpoint_scans']['Row']>;

export type LiveOccurrence = V['occurrences_live']['Row'] & { org_id: string };
export type PatrolDetailed = V['patrols_detailed']['Row'] & { org_id: string };

// Tables introduced by the multi-tenant migration (manual types until
// database.types.ts is regenerated).
export interface Organization {
  id: string;
  name: string;
  slug: string;
  legal_name: string | null;
  contact_email: string | null;
  contact_phone: string | null;
  address: string | null;
  logo_url: string | null;
  primary_color: string | null;
  is_active: boolean;
  plan: string;
  max_users: number | null;
  max_sites: number | null;
  trial_ends_at: string | null;
  created_at: string;
  updated_at: string;
}

export type ManagerDecision = 'acknowledged' | 'escalated' | 'rejected';

// ----------------------------------------------------------------------------
// Filter + saved-view shapes (used by /occurrences/all and similar surfaces)
// ----------------------------------------------------------------------------
export interface OccurrencesFilter {
  q?: string;
  status?: OccurrenceStatus | '';
  severity?: SeverityLevel | '';
  site_id?: string;
  site_name?: string;
  type?: string;
  from?: string;        // ISO date (inclusive)
  to?: string;          // ISO date (inclusive)
  logged_by?: string;
  is_patrol?: '' | 'true' | 'false';
}

export const OCCURRENCE_FILTER_KEYS: (keyof OccurrencesFilter)[] = [
  'q', 'status', 'severity', 'site_id', 'site_name', 'type',
  'from', 'to', 'logged_by', 'is_patrol',
];

// ----------------------------------------------------------------------------
// Tasks (mirrors public.tasks)
// ----------------------------------------------------------------------------
export type TaskStatus = 'open' | 'in_progress' | 'blocked' | 'done' | 'cancelled';
export type TaskPriority = 'low' | 'normal' | 'high' | 'urgent';

export interface Task {
  id: number;
  org_id: string;
  title: string;
  description: string | null;
  priority: TaskPriority;
  status: TaskStatus;
  assigned_to: string | null;
  assigned_to_name: string | null;
  assigned_by: string | null;
  assigned_by_name: string | null;
  occurrence_id: number | null;
  ob_number: string | null;
  due_at: string | null;
  completed_at: string | null;
  completed_by: string | null;
  completion_notes: string | null;
  created_at: string;
  updated_at: string;
}

export interface TaskUpdate {
  id: number;
  task_id: number;
  previous_status: TaskStatus | null;
  new_status: TaskStatus;
  notes: string | null;
  updated_by: string | null;
  updated_by_name: string | null;
  created_at: string;
}

export const TASK_STATUSES: TaskStatus[] = ['open','in_progress','blocked','done','cancelled'];
export const TASK_STATUS_LABELS: Record<TaskStatus, string> = {
  open: 'Open',
  in_progress: 'In Progress',
  blocked: 'Blocked',
  done: 'Done',
  cancelled: 'Cancelled',
};
export const TASK_STATUS_COLORS: Record<TaskStatus, string> = {
  open: '#3b82f6',
  in_progress: '#0ea5e9',
  blocked: '#dc2626',
  done: '#16a34a',
  cancelled: '#64748b',
};

export const TASK_PRIORITIES: TaskPriority[] = ['low','normal','high','urgent'];
export const TASK_PRIORITY_LABELS: Record<TaskPriority, string> = {
  low: 'Low', normal: 'Normal', high: 'High', urgent: 'Urgent',
};
export const TASK_PRIORITY_COLORS: Record<TaskPriority, string> = {
  low: '#64748b', normal: '#3b82f6', high: '#ea580c', urgent: '#dc2626',
};

export interface OccurrenceComment {
  id: number;
  org_id: string | null;
  occurrence_id: number;
  ob_number: string | null;
  author_id: string | null;
  author_name: string | null;
  body: string;
  edited_at: string | null;
  created_at: string;
}

export interface SavedView {
  id: string;
  org_id: string | null;
  user_id: string;
  scope: 'occurrences' | string;
  name: string;
  filters: OccurrencesFilter;
  is_pinned: boolean;
  is_shared: boolean;
  created_at: string;
  updated_at: string;
}

export interface ManagerAcknowledgement {
  id: number;
  org_id: string;
  occurrence_id: number;
  ob_number: string | null;
  reviewed_by: string | null;
  reviewed_by_name: string | null;
  decision: ManagerDecision;
  manager_notes: string | null;
  signature_data_url: string | null;
  reviewed_at: string;
  created_at: string;
}
